# Generated by Django 5.2.17 on 2026-09-20 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('porcentaje_avance', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('En Curso', 'En Curso'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado')], default='En Curso', max_length=20)),
                ('cliente', models.ForeignKey(limit_choices_to={'role': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_cliente', to=settings.AUTH_USER_MODEL)),
                ('empleado_encargado', models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLEADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=150, verbose_name='Nombre/Descripción')),
                ('archivo', models.FileField(upload_to='documentos_obras/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='proyectos.proyecto')),
            ],
        ),
    ]
